# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:stringstatic
# ======================================================================

`%||%` <- function(lhs, rhs) {
  if (length(lhs) == 0) {
    return(rhs)
  }
  lhs
}

str_extract <- function(string, pattern) {
  is_fixed <- inherits(pattern, "fixed")
  ignore.case <- attr(pattern, "options")$case_insensitive %||% FALSE

  regmatches(
    x = string,
    m = regexpr(
      pattern = pattern,
      text = string,
      ignore.case = ignore.case,
      perl = !is_fixed,
      fixed = is_fixed
    )
  )
}
